/* eslint-disable @typescript-eslint/no-deprecated -- tseslint.config() is the only way to use extends; core defineConfig has incompatible API */
import { includeIgnoreFile } from "@eslint/config-helpers";
import eslint from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import eslintPluginAstro from "eslint-plugin-astro";
import jsxA11y from "eslint-plugin-jsx-a11y";
import pluginReact from "eslint-plugin-react";
import reactCompiler from "eslint-plugin-react-compiler";
import eslintPluginReactHooks from "eslint-plugin-react-hooks";
import path from "node:path";
import tseslint from "typescript-eslint";

const gitignorePath = path.resolve(import.meta.dirname, ".gitignore");

const baseConfig = tseslint.config({
  extends: [eslint.configs.recommended, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
  languageOptions: {
    parserOptions: {
      projectService: true,
      tsconfigRootDir: import.meta.dirname,
    },
  },
  rules: {
    "no-console": "warn",
    "no-unused-vars": "off",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
    "@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
  },
});

const reactConfig = tseslint.config({
  files: ["**/*.{js,jsx,ts,tsx}"],
  extends: [pluginReact.configs.flat.recommended],
  languageOptions: {
    ...pluginReact.configs.flat.recommended.languageOptions,
    globals: {
      window: true,
      document: true,
    },
  },
  plugins: {
    "react-hooks": eslintPluginReactHooks,
    "react-compiler": reactCompiler,
  },
  settings: { react: { version: "detect" } },
  rules: {
    ...eslintPluginReactHooks.configs.recommended.rules,
    "react/react-in-jsx-scope": "off",
    "react-compiler/react-compiler": "error",
  },
});

// `jsxA11y.flatConfigs.strict` ships without a `files` key, so it must be spread
// with an explicit scope — unscoped it would apply its rules *and* its
// `parserOptions.ecmaFeatures.jsx` to .astro/.ts files, colliding with astroConfig's
// dedicated parser block below.
// eslint-plugin-jsx-a11y ships no type declarations, so everything read off it is
// `any` — hence the narrow disable rather than a repo-wide one.
/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access -- untyped plugin, see above */
/** @type {import("eslint").Linter.Config} */
const jsxA11yConfig = {
  ...jsxA11y.flatConfigs.strict,
  files: ["**/*.{jsx,tsx}"],
  // `flatConfigs.strict` registers the plugin as a fresh wrapper object, but
  // astro's flat/jsx-a11y-recommended (below) already registers the plugin's
  // default export under the same "jsx-a11y" key — and ESLint rejects a redefine
  // with a different object. Pin both registrations to the same instance.
  plugins: { "jsx-a11y": jsxA11y },
};
/* eslint-enable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access */

const astroConfig = tseslint.config({
  files: ["**/*.astro"],
  languageOptions: {
    parserOptions: {
      // Parse the TypeScript in .astro frontmatter (interface/type/type-imports).
      parser: tseslint.parser,
      extraFileExtensions: [".astro"],
    },
  },
  rules: {
    "astro/no-set-html-directive": "error",
    "astro/no-unused-css-selector": "warn",
    "astro/prefer-class-list-directive": "warn",
  },
});

// The Astro parser doesn't forward the type information that typescript-eslint's
// type-checked rules require, so disable them for .astro files (and the <script>
// blocks the Astro processor extracts) to avoid "requires type information" crashes.
const astroDisableTypeChecked = tseslint.config({
  files: ["**/*.astro", "**/*.astro/*.ts", "**/*.astro/*.js"],
  extends: [tseslint.configs.disableTypeChecked],
});

export default tseslint.config(
  includeIgnoreFile(gitignorePath),
  // Generated by `npm run db:types` — don't lint/format machine output.
  // `supabase/.temp/**` is transient stack state (ignored via supabase/.gitignore,
  // which the root includeIgnoreFile above doesn't pick up).
  { ignores: ["src/db/database.types.ts", "supabase/.temp/**"] },
  baseConfig,
  reactConfig,
  jsxA11yConfig,
  eslintPluginAstro.configs["flat/recommended"],
  ...eslintPluginAstro.configs["flat/jsx-a11y-recommended"],
  astroConfig,
  astroDisableTypeChecked,
  eslintPluginPrettier,
);
